=== Vivek-Kamble/XML/VScode/product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="Myproduct">
  <xs:element name="product">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="pname" type="xs:string">
                  <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:minLength value="3"></xs:minLength>
                        <xs:maxLength value="20"></xs:maxLength>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:element>
              <xs:element name="price" type="xs:integer">
                  <xs:complexType>
                      <xs:simpleContent>
                          <xs:extension base="xs:string">
                              <xs:attribute name="currency" type="xs:String" default="INR"></xs:attribute>
                          </xs:extension>
                      </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
              <xs:element name="mfgdate" type="xs:date"></xs:element>
              <xs:element name="mfgtime" type="xs:time"></xs:element>
              <xs:element name="discount" type="xs:boolean"></xs:element>
              <xs:element name="drate" type="xs:decimal">
                  <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                          <xs:minInclusive value="0"></xs:minInclusive>
                          <xs:maxInclusive value="100"></xs:maxInclusive>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:element>
              <xs:element name="pcode" type="xs:string">
                  <xs:simpleType>
                      <xs:restriction base="xs:string">
                          <!--IND12345
                          three ca[pital lettrers and 5 numbers
                          -->
                          <xs:pattern value="[A-Z]{3}[0-9]{5}"></xs:pattern>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:integer" use="required"></xs:attribute>
          <xs:attribute name="company" type="xs:string" fixed="DEF Products Ltd."></xs:attribute>
          <xs:attribute name="currency" type="xs:string" default="INR">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:enumeration value="INR"></xs:enumeration>
                      <xs:enumeration value="GBP"></xs:enumeration>
                      <xs:enumeration value="USD"></xs:enumeration>
                      <xs:enumeration value="SGD"></xs:enumeration>
                  </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
      </xs:complexType>  
  </xs:element>
</xs:schema>

=== Vivek-Kamble/XML/VScode/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<product xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Myproduct product.xsd" xmlns="Myproduct" id="1" company="DEF Products Ltd.">
       <pname>Shampoo</pname>
       <price>123</price>
       <mfgdate>1999-02-03</mfgdate>
       <mfgtime>15:03:45</mfgtime>
       <discount>true</discount>
       <drate>10.25</drate>
       <pcode>INA45412</pcode>
</product>
